
# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Setup term for programs to be able to use it
env:
  TERM: xterm-256color-italic #xterm-256color

window:
  # Spread additional padding evenly around the terminal content.
  dynamic_padding: true

  # Startup Mode (changes require restart)
  startup_mode: Windowed

# Sample Font configuration for font: Monoid.
# Feel free to use different font configuration family & face for each sections
font:
  # Normal font face - Also used to draw glyphs on tmux & VIM
  # NOTE: You may use any font you'd like but make sure the normal fonts
  # support ligatures/glyphs. That's used by tmux & VIM to provide a better
  # UI for powerline & tmux bottom bar.
  normal:
    # Font name
    family: MesloLGS NF #BlexMono Nerd Font
    # Font face
    style: Regular

  # Bold font face
  bold:
    family: Menlo #Monoid
    style: Bold

  # Italic font face
  italic:
    family: Menlo #Monoid
    style: Italic

  # Bold italic font face
  # Note: Since i don't have a font italic version of this font, I just specified
  # italic & it just works. You may specifiy the bold italic version if it exists
  # for your font
  bold_italic:
    family: Monoid
    style: Italic

  # Font size
  size: 13.0
  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing
  # I've given in 14 spacing which fits really well with my fonts, you may change it
  # to your convenience but make sure to adjust 'glyph_offset' appropriately post that
  offset:
   x: 0
   y: 14

  # Note: This requires RESTART
  # By default when you change the offset above you'll see an issue, where the texts are bottom
  # aligned with the cursor, this is to make sure they center align.
  # This offset should usually be 1/2 of the above offset-y being set.
  glyph_offset:
   x: 0
   # Keeping this as half of offset to vertically align the text in cursor
   y: 7

  # Better font rendering for mac
  use_thin_strokes: true

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

# Live config reload (changes require restart)
live_config_reload: true

draw_bold_text_with_bright_colors: true

hide_cursor_when_typing: true

schemes:
  monokai_pro: &monokai
    primary:
      background: '#2D2A2E'
      foreground: '#FCFCFA'

    # Normal colors
    normal:
      black:   '#403E41'
      red:     '#FF6188'
      green:   '#A9DC76'
      yellow:  '#FFD866'
      blue:    '#FC9867'
      magenta: '#AB9DF2'
      cyan:    '#78DCE8'
      white:   '#FCFCFA'

    # Bright colors
    bright:
      black:   '#727072'
      red:     '#FF6188'
      green:   '#A9DC76'
      yellow:  '#FFD866'
      blue:    '#FC9867'
      magenta: '#AB9DF2'
      cyan:    '#78DCE8'
      white:   '#FCFCFA'
  gruvbox: &gruvbox
    # Default colors
    primary:
      # hard contrast: background = '#1d2021'
      background: '#282828'
      # soft contrast: background = '#32302f'
      foreground: '#ebdbb2'

    # Normal colors
    normal:
      black:   '#282828'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#a89984'

    # Bright colors
    bright:
      black:   '#928374'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'

colors: *monokai

key_bindings:
  - { key: T, mods: Command, chars: "\x06\x63" }
